// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggpefjefbcdbscgdgrwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncGVmamVmYmNkYnNjZ2Rncnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODU1ODYsImV4cCI6MjA3MTM2MTU4Nn0.HNwTmP7GHKvZxXI6Kaugl8IyhFf0h35Nb-BVhSyFbAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});